---
title: "Lab2_Peknevych_PM12"
author: "Peknevych Illia"
date: "2022-10-05"
output: html_document
---

# Лабораторна робота 2.

### Дисципліна: Прикладна аналітика при розробці.

### Студент: Пекневич Ілля Ігорович, УП-12.

#### 1. Створіть вектор v із 100 елементів командою v \<- rnorm(100).

```{r}
v <- rnorm(100)
v
```

#### Для цього вектору виведіть:

####10-й елемент:

```{r}
v[10]
```

#### Елементи з 10-го по 20-й включно:

```{r}
v[10:20]
```

#### 10 елементів починаючи з 20-го:

```{r}
v[20:30]
```

#### Елементи більше 0:

```{r}
v[v > 0]
```

#### 2. Створіть фрейм (data frame) y командою y \<- data.frame(a = rnorm(100), b = 1:100, cc = sample(letters, 100, replace = TRUE)).

```{r}
y <- data.frame(a = rnorm(100), b = 1:100, cc = sample(letters, 100, replace = TRUE))
y
```

#### Для цього data frame виведіть:

#### Останні 10 строк:

```{r}
tail(y, 10)
```

#### Строки з 10 по 20 включно:

```{r}
 y[10:20,]
```

#### 10-й елемент стовпця b:

```{r}
y$b[10]
```

#### Повністю стовпець cc, при цьому використайте ім'я стовпця:

```{r}
y$cc
```

## \#### 3. Створіть вектор z з елементами 1, 2, 3, NA, 4, NA, 5, NA. підрахуйте середнє значення всіх елементів цього вектору без NA значень та з NA значеннями.

```{r}
z <- c(1, 2, 3, NA, 4, NA, 5, NA)
z
```

#### Для цього вектору:

#### Виведіть всі елементи, які не NA:

```{r}
z[!is.na(z)]
```

#### Підрахуйте середнє значення всіх елементів цього вектору без NA значень:

```{r}
mean(z[!is.na(z)])
```

#### Та з NA значеннями:

```{r}
mean(z)
```
